import { supabase } from './supabaseClient';

export interface FormCreationResult {
  formId: string;
  responderUri: string;
}

export interface StudentRecord {
  name: string;
  email: string;
}

const getAccessToken = async (): Promise<string> => {
  if (!supabase) throw new Error("Authentication infrastructure offline.");
  const { data: { session } } = await supabase.auth.getSession();
  const token = session?.provider_token;
  if (!token) throw new Error("This action requires a Google Session. Please re-authenticate via Google SSO.");
  return token;
};

async function handleResponse(res: Response) {
  if (!res.ok) {
    const data = await res.json().catch(() => ({}));
    throw new Error(data.error?.message || `Google API error: ${res.status}`);
  }
  return res.json();
}

/**
 * Parses a Google Sheets URL to extract the ID.
 */
export const extractSheetId = (url: string): string | null => {
  const match = url.match(/\/spreadsheets\/d\/([a-zA-Z0-9-_]+)/);
  return match ? match[1] : null;
};

/**
 * Fetches student roster from a Google Sheet.
 */
export const fetchStudentsFromSheet = async (sheetUrl: string): Promise<StudentRecord[]> => {
  const sheetId = extractSheetId(sheetUrl);
  if (!sheetId) throw new Error("Invalid Google Sheets URL format.");
  
  const token = await getAccessToken();
  const res = await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${sheetId}/values/A:B`, {
    headers: { 'Authorization': `Bearer ${token}` }
  });
  const data = await handleResponse(res);
  
  if (!data.values || data.values.length === 0) return [];
  
  // Skip header if it looks like one
  const rows = (data.values[0][0].toLowerCase().includes('name')) ? data.values.slice(1) : data.values;
  
  return rows.map((row: any) => ({
    name: row[0] || 'Student',
    email: row[1] || ''
  })).filter((s: any) => s.email.includes('@'));
};

/**
 * Creates a new autograded Google Form Quiz.
 * v7.3: Moves description to batchUpdate to fix API "Only title allowed" error.
 */
export const createGoogleFormQuiz = async (
  title: string,
  questions: any[],
  deadline?: string
): Promise<FormCreationResult> => {
  const token = await getAccessToken();
  const headers = {
    'Authorization': `Bearer ${token}`,
    'Content-Type': 'application/json'
  };

  // 1. Create the Form with ONLY title (API Limit Requirement)
  const createRes = await fetch('https://forms.googleapis.com/v1/forms', {
    method: 'POST',
    headers,
    body: JSON.stringify({ 
      info: { 
        title: title
      } 
    })
  });
  const form = await handleResponse(createRes);
  const formId = form.formId;

  // 2. Prepare Batch Update (Settings + Metadata + Items)
  const description = `Project: ${title}.\n${deadline ? `DUE DATE: ${deadline}` : ''}\n\nThis assessment was autonomously generated by LabGen Studio based on analyzed laboratory protocols. Review scientific concepts carefully before submission.`;

  const requests: any[] = [
    // Update Info (Description must be set here)
    {
      updateFormInfo: {
        info: {
          description: description
        },
        updateMask: 'description'
      }
    },
    // Enable Quiz mode
    {
      updateSettings: {
        settings: { quizSettings: { isQuiz: true } },
        updateMask: 'quizSettings.isQuiz'
      }
    }
  ];

  // Add questions to batch
  questions.forEach((q, index) => {
    requests.push({
      createItem: {
        item: {
          title: q.question,
          questionItem: {
            question: {
              required: true,
              grading: {
                pointValue: q.points || 1,
                correctAnswers: {
                  answers: [{ value: q.options[q.correctIndex] }]
                },
                whenRight: { text: `Validated. ${q.explanation}` },
                whenWrong: { text: `Review required. ${q.explanation}` }
              },
              choiceQuestion: {
                type: 'RADIO',
                options: q.options.map((opt: string) => ({ value: opt }))
              }
            }
          }
        },
        location: { index }
      }
    });
  });

  const updateRes = await fetch(`https://forms.googleapis.com/v1/forms/${formId}:batchUpdate`, {
    method: 'POST',
    headers,
    body: JSON.stringify({ requests })
  });
  await handleResponse(updateRes);

  return {
    formId,
    responderUri: form.responderUri
  };
};