
import { Scene } from "../types";

/**
 * Generates a professional academic print-ready HTML structure from Markdown.
 * This utilizes the browser's native print-to-PDF capabilities with scientific styling.
 * Now supports dynamic document types for Educator (v3) and Learner (v4).
 */
export const exportMarkdownAsPDF = (projectName: string, markdown: string, docType: 'Educator Manual' | 'Laboratory Report' = 'Educator Manual') => {
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;

  const primaryColor = docType === 'Educator Manual' ? '#1e3a8a' : '#0f172a';
  const secondaryColor = docType === 'Educator Manual' ? '#3b82f6' : '#6366f1';

  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${projectName} - ${docType}</title>
      <link href="https://fonts.googleapis.com/css2?family=Crimson+Pro:ital,wght@0,400;0,700;1,400&family=Inter:wght@400;700;900&display=swap" rel="stylesheet">
      <style>
        body {
          font-family: 'Crimson Pro', serif;
          line-height: 1.6;
          color: #1a1a1a;
          padding: 60px;
          max-width: 850px;
          margin: 0 auto;
        }
        h1, h2, h3, h4 {
          font-family: 'Inter', sans-serif;
          font-weight: 900;
          text-transform: uppercase;
          letter-spacing: -0.02em;
          color: ${primaryColor};
          margin-top: 1.5em;
          margin-bottom: 0.5em;
        }
        h1 { font-size: 26pt; border-bottom: 4px solid ${primaryColor}; padding-bottom: 15px; margin-top: 0; }
        h2 { font-size: 18pt; border-bottom: 1px solid #e2e8f0; padding-bottom: 5px; margin-top: 2em; }
        h3 { font-size: 14pt; color: ${secondaryColor}; }
        p { font-size: 12pt; margin-bottom: 1.2em; text-align: justify; }
        strong { font-weight: 700; color: #000; }
        ul, ol { margin-bottom: 1.5em; padding-left: 25px; }
        li { font-size: 12pt; margin-bottom: 0.6em; }
        .header-meta {
          font-family: 'Inter', sans-serif;
          font-size: 9pt;
          font-weight: 700;
          color: #64748b;
          text-transform: uppercase;
          letter-spacing: 0.15em;
          margin-bottom: 50px;
          display: flex;
          justify-content: space-between;
          border-bottom: 1px solid #f1f5f9;
          padding-bottom: 12px;
        }
        .doc-tag {
            display: inline-block;
            background: ${primaryColor};
            color: white;
            padding: 4px 12px;
            border-radius: 4px;
            font-size: 8pt;
            margin-bottom: 20px;
        }
        .footer {
          margin-top: 60px;
          font-family: 'Inter', sans-serif;
          font-size: 8pt;
          color: #94a3b8;
          text-align: center;
          border-top: 1px solid #f1f5f9;
          padding-top: 25px;
        }
        @media print {
          body { padding: 0; }
          .no-print { display: none; }
          button { display: none; }
        }
      </style>
    </head>
    <body>
      <div class="header-meta">
        <span>LabGen Studio v4.0 Alpha</span>
        <span>${new Date().toLocaleDateString()}</span>
      </div>
      <div class="doc-tag">${docType}</div>
      <div id="content"></div>
      <div class="footer">
        Generated by LabGen Studio - Multimodal Scientific Production Engine
      </div>
    </body>
    </html>
  `;

  printWindow.document.write(htmlContent);

  const contentEl = printWindow.document.getElementById('content');
  if (contentEl) {
    const lines = markdown.split('\n');
    let html = '';
    let inList = false;
    let listType = '';

    lines.forEach(line => {
      const trimmedLine = line.trim();
      
      if (inList && !trimmedLine.match(/^([-*]|\d+\.)/)) {
        html += listType === 'ul' ? '</ul>' : '</ol>';
        inList = false;
      }

      if (trimmedLine.startsWith('# ')) {
        html += `<h1>${trimmedLine.substring(2)}</h1>`;
      } else if (trimmedLine.startsWith('## ')) {
        html += `<h2>${trimmedLine.substring(3)}</h2>`;
      } else if (trimmedLine.startsWith('### ')) {
        html += `<h3>${trimmedLine.substring(4)}</h3>`;
      } else if (trimmedLine.match(/^\d+\./)) {
        if (!inList) { html += '<ol>'; inList = true; listType = 'ol'; }
        html += `<li>${processMD(trimmedLine.replace(/^\d+\.\s*/, ''))}</li>`;
      } else if (trimmedLine.startsWith('- ') || trimmedLine.startsWith('* ')) {
        if (!inList) { html += '<ul>'; inList = true; listType = 'ul'; }
        html += `<li>${processMD(trimmedLine.substring(2))}</li>`;
      } else if (trimmedLine === '') {
        // Skip
      } else {
        html += `<p>${processMD(trimmedLine)}</p>`;
      }
    });

    if (inList) html += listType === 'ul' ? '</ul>' : '</ol>';
    contentEl.innerHTML = html;
  }

  function processMD(text: string) {
    return text
        .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
        .replace(/\*(.*?)\*/g, '<em>$1</em>');
  }

  printWindow.document.close();
  
  setTimeout(() => {
    printWindow.focus();
    printWindow.print();
  }, 800);
};
